### ISSUE TITLE
First Tasks

### ISSUE THREAD

**Issue by ignas-old** [Ignas-Vaitkus/content-management-system#1]
## Description
These tasks are required to fulfill the requirements of the project
## Tasks
- [x]  Write SQL script to prepare mysql database for ORM.
- [x]  Implement Pages Entity.
- [x]  Add seeder to populate database with page titles and content.
- [x]  Write database generated pages for regular user to interact with.
- [x]  Write the content management layer.
- [x]  Add a pseudo-authentication layer to access content management layer.
